import os
import webbrowser
from dotenv import load_dotenv
from linkedin_agent import LinkedInPostGenerator




def save_post_to_file(post: str, language: str) -> str:
    safe_lang = language.strip().lower().replace(" ", "_") or "output"
    output_path = f"linkedin_post_{safe_lang}.txt"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(post)
    return output_path


def save_post_to_html(post: str, language: str) -> str:

        safe_lang = language.strip().lower().replace(" ", "_") or "output"
        output_path = f"linkedin_post_{safe_lang}.html"
        paragraphs = [p.strip() for p in post.split("\n\n") if p.strip()]
        body = "\n".join(f"<p>{p}</p>" for p in paragraphs)

        html = f"""<!doctype html>
<html lang="bn">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Generated LinkedIn Post</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;500;600;700&family=Hind+Siliguri:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {{
            color-scheme: light;
        }}
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            padding: 40px 20px;
            font-size: 18px;
            line-height: 1.9;
            color: #1a1a2e;
            background: linear-gradient(135deg, #e8f0fe 0%, #f0e6ff 50%, #fce4ec 100%);
            font-family: "Noto Sans Bengali", "Hind Siliguri", "Kalpurush", sans-serif;
            min-height: 100vh;
        }}
        .card {{
            max-width: 720px;
            margin: 0 auto;
            background: #ffffff;
            border-radius: 16px;
            padding: 36px 32px;
            box-shadow: 0 8px 30px rgba(0,0,0,0.08);
        }}
        .card-header {{
            display: flex;
            align-items: center;
            gap: 12px;
            margin-bottom: 24px;
            padding-bottom: 16px;
            border-bottom: 1px solid #e8e8e8;
        }}
        .avatar {{
            width: 48px;
            height: 48px;
            border-radius: 50%;
            background: linear-gradient(135deg, #0077b5, #00a0dc);
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: 700;
            font-size: 20px;
        }}
        .card-header-text {{
            display: flex;
            flex-direction: column;
        }}
        .card-header-text .name {{
            font-weight: 600;
            font-size: 16px;
            color: #111;
        }}
        .card-header-text .meta {{
            font-size: 13px;
            color: #666;
        }}
        .badge {{
            margin-left: auto;
            background: #e8f4fd;
            color: #0077b5;
            font-size: 12px;
            font-weight: 600;
            padding: 4px 10px;
            border-radius: 12px;
        }}
        p {{
            margin: 0 0 18px 0;
            color: #2c2c2c;
        }}
        p:last-child {{
            margin-bottom: 0;
        }}
        .footer {{
            margin-top: 24px;
            padding-top: 16px;
            border-top: 1px solid #e8e8e8;
            font-size: 13px;
            color: #888;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="card">
        <div class="card-header">
            <div class="avatar">in</div>
            <div class="card-header-text">
                <span class="name">LinkedIn Post Preview</span>
                <span class="meta">Generated Post &bull; {language}</span>
            </div>
            <span class="badge">AI Generated</span>
        </div>
        {body}
        <div class="footer">
            Generated by LinkedIn Post Generator.
        </div>
    </div>
</body>
</html>
"""

        with open(output_path, "w", encoding="utf-8") as f:
                f.write(html)
        return output_path

def main():
    # Step 1: Load API key.
    load_dotenv()

    # Step 2: Init the AI Agent
    print("\n LinkedIn Post Generator")
    print("--------------------------")
    
    try:
        agent = LinkedInPostGenerator()
    except Exception as e:
        print(f" Error: {e}")
        return
    
    # Step 3: Get user input
    topic = input(" Enter post topic: ").strip()
    language = input(" Enter language (e.g., English, Bengali, Spanish): ").strip()
    
    if not topic or not language:
        print(" Topic and language are required.")
        return

    # Step 4: Generate the post
    print("\n Generating your post... Please wait.\n")
    try:
        post = agent.generate_post(topic, language)
    except Exception as error:
        print(" Failed to generate post:")
        print(str(error))
        return
    
    # Step 5: Save files
    text_file_path = save_post_to_file(post, language)
    html_file_path = save_post_to_html(post, language)
    html_abs_path = os.path.abspath(html_file_path)

    # Step 6: Display output summary
    print(" Post generated successfully!")
    print(f"   Language: {language}")
    print(f"   Length:   {len(post)} characters, {len(post.split())} words")
    print()
    
    print(f" Files saved:")
    print(f"    Text: {text_file_path}")
    print(f"    HTML: {html_file_path}")

    # Always auto-open the HTML in the default browser
    print("\n Opening your post in the browser...")
    webbrowser.open(f"file://{html_abs_path}")
    print(f"   If it didn't open, manually open:\n   {html_abs_path}")

if __name__ == "__main__":
    main()
